// apps/demo-react/src/components/todo-list/new-todo-item-form.view.tsx
interface NewTodoItemFormViewProps {
  text: string;
  onChange: (value: string) => void;
  onSubmit: () => void;
  disabled: boolean;
}

export function NewTodoItemFormView({
  text,
  onChange,
  onSubmit,
  disabled,
}: NewTodoItemFormViewProps) {
  return (
    <div className="todo-input-group">
      <input
        type="text"
        value={text}
        onChange={(e) => onChange(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            onSubmit();
          }
        }}
        placeholder="Add a new todo..."
      />
      <button disabled={disabled || !text.trim()} onClick={onSubmit}>
        Add Todo
      </button>
    </div>
  );
}

// apps/demo-svelte/src/components/todo-list/new-todo-item-form.view.svelte
<script lang="ts">
  interface Props {
    text: string;
    onChange: (value: string) => void;
    onSubmit: () => void;
    disabled: boolean;
  }

  let { text, onChange, onSubmit, disabled }: Props = $props();
</script>

<div class="todo-input-group">
  <input
    type="text"
    value={text}
    oninput={(e) => onChange(e.currentTarget.value)}
    placeholder="Add a new todo"
    onkeydown={(e) => {
      if (e.key === "Enter") {
        onSubmit();
      }
    }}
  />
  <button onclick={onSubmit} disabled={disabled || !text.trim()}>
    Add Todo
  </button>
</div>
