// apps/demo-svelte/src/components/todo-list/history.connector.svelte
<script lang="ts">
  import { TodoListService } from "@xndrjs/demo-common";
  import { reactiveValue } from "@xndrjs/adapter-svelte";
  import TodoHistoryView from "./todo-history.view.svelte";

  interface Props {
    todoListService: TodoListService;
  }

  let { todoListService }: Props = $props();

  const historyStore = reactiveValue(() => todoListService.history);
  const historyPointerStore = reactiveValue(() => todoListService.historyPointer);
</script>

<div class="demo-section">
  <h2>Memento History</h2>
  <TodoHistoryView history={$historyStore} historyPointer={$historyPointerStore} />
</div>

// apps/demo-react/src/components/todo-list/history.connector.tsx
import { useReactiveValue } from "@xndrjs/adapter-react";
import { TodoListService } from "@xndrjs/demo-common";
import { TodoHistoryView } from "./todo-history.view";

interface TodoHistoryConnectorProps {
  todoListService: TodoListService;
}

export function TodoHistoryConnector({
  todoListService,
}: TodoHistoryConnectorProps) {
  const history = useReactiveValue(todoListService.history);
  const historyPointer = useReactiveValue(todoListService.historyPointer);

  return (
    <div className="demo-section">
      <h2>Memento History</h2>
      <TodoHistoryView history={history} historyPointer={historyPointer} />
    </div>
  );
}
