// apps/demo-svelte/src/components/todo-list/todo-list.connector.svelte
<script lang="ts">
  import { TodoListService, NewTodoItemForm } from "@xndrjs/demo-common";
  import { reactiveValue, toStatePort, useViewModel } from "@xndrjs/adapter-svelte";
  import NewTodoItemFormView from "./new-todo-item-form.view.svelte";
  import TodoListView from "./todo-list.view.svelte";

  interface Props {
    todoListService: TodoListService;
  }

  let { todoListService }: Props = $props();

  // example: using a Svelte Rune as state
  let newTodoTextStore = $state("");
  // converting the Rune as State Port to be used inside a Xandr class
  const newTodoTextPort = toStatePort(() => newTodoTextStore, (v) => newTodoTextStore = v);
  // passing the State Port to the Xandr class
  const newTodoItemForm = useViewModel(() => new NewTodoItemForm(newTodoTextPort, todoListService));
  // using reactive values from the Xandr class
  const todosStore = reactiveValue(() => todoListService.todos);
  const canUndoStore = reactiveValue(() => todoListService.canUndo);
  const canRedoStore = reactiveValue(() => todoListService.canRedo);
</script>

<div class="demo-section">
  <h2>Todo List</h2>
  <NewTodoItemFormView
    text={newTodoTextStore}
    onChange={(value) => newTodoTextPort.set(value)}
    onSubmit={() => newTodoItemForm.submit()}
    disabled={false}
  />
  <TodoListView
    todos={$todosStore}
    onToggle={(id) => todoListService.toggleTodo(id)}
    onDelete={(id) => todoListService.removeTodo(id)}
  />
  <div class="todo-actions">
    <button onclick={() => todoListService.undo()} disabled={!$canUndoStore}>
      Undo
    </button>
    <button onclick={() => todoListService.redo()} disabled={!$canRedoStore}>
      Redo
    </button>
  </div>
</div>

// apps/demo-react/src/components/todo-list/todo-list.connector.tsx
import { useCreateStatePort, useViewModel } from "@xndrjs/adapter-react";
import { TodoListService, NewTodoItemForm } from "@xndrjs/demo-common";
import { TodoListView } from "./todo-list.view";
import { useReactiveValue } from "@xndrjs/adapter-react";
import { NewTodoItemFormView } from "./new-todo-item-form.view";
import { useMonitorStatePort, useMonitorMemento } from "@xndrjs/devtools-react";

interface TodoHistoryConnectorProps {
  todoListService: TodoListService;
}

export function TodoListConnector({
  todoListService,
}: TodoHistoryConnectorProps) {
  const newTodoTextPort = useCreateStatePort<string>("");
  const newTodoItemForm = useViewModel(
    () => new NewTodoItemForm(newTodoTextPort, todoListService),
  );

  const todos = useReactiveValue(todoListService.todos);
  const canUndo = useReactiveValue(todoListService.canUndo);
  const canRedo = useReactiveValue(todoListService.canRedo);
  const newTodoText = useReactiveValue(newTodoTextPort);

  // Monitor StatePorts automatically (handles both ReactiveValue and ComputedValue)
  useMonitorStatePort(todoListService.canUndo, { name: "TodoList.canUndo" });
  useMonitorStatePort(todoListService.canRedo, { name: "TodoList.canRedo" });

  // Monitor Memento caretaker for DevTools
  useMonitorMemento(todoListService.caretaker, { name: "TodoList.Memento" });

  return (
    <div className="demo-section">
      <h2>Todo List</h2>
      <NewTodoItemFormView
        text={newTodoText}
        onChange={(value) => newTodoTextPort.set(value)}
        onSubmit={() => newTodoItemForm.submit()}
        disabled={false}
      />
      <TodoListView
        todos={todos}
        onToggle={(id) => todoListService.toggleTodo(id)}
        onDelete={(id) => todoListService.removeTodo(id)}
      />
      <div className="todo-actions">
        <button onClick={() => todoListService.undo()} disabled={!canUndo}>
          Undo
        </button>
        <button onClick={() => todoListService.redo()} disabled={!canRedo}>
          Redo
        </button>
      </div>
    </div>
  );
}
