// packages/adapter-react/src/use-view-model.ts
import { useRef, useEffect } from "react";
import type { ViewModel } from "@xndrjs/core";

/**
 * Hook that creates and manages a ViewModel instance with automatic cleanup.
 * The ViewModel is created once and automatically disposed when the component unmounts.
 *
 * In React Strict Mode (development), the cleanup function runs twice. This hook
 * handles this by checking if the ViewModel has been disposed and recreating it
 * if necessary, ensuring subscriptions continue to work correctly.
 *
 * @param factory - Function that creates the ViewModel instance (called only once, or when recreated after dispose)
 * @returns The ViewModel instance
 *
 * @example
 * ```tsx
 * import { useViewModel } from '@xndrjs/adapter-react';
 * import { useReactiveValue } from '@xndrjs/adapter-react';
 *
 * class CounterVM extends ViewModel {
 *   count = new ReactiveValue(0);
 *   doubled = createComputed(this.count)
 *     .as((c) => c * 2)
 *     .for(this);
 *
 *   increment() {
 *     this.count.set((prev) => prev + 1);
 *   }
 * }
 *
 * function Counter() {
 *   const vm = useViewModel(() => new CounterVM());
 *   const count = useReactiveValue(vm.count);
 *   const doubled = useReactiveValue(vm.doubled);
 *
 *   return (
 *     <div>
 *       <div>Count: {count}</div>
 *       <div>Doubled: {doubled}</div>
 *       <button onClick={() => vm.increment()}>+</button>
 *     </div>
 *   );
 * }
 * ```
 */
export function useViewModel<T extends ViewModel>(factory: () => T): T {
  const ref = useRef<T | null>(null);

  // Create instance if it doesn't exist or has been disposed
  // This handles React Strict Mode where cleanup runs twice
  if (ref.current === null || ref.current.disposed) {
    ref.current = factory();
  }

  useEffect(() => {
    return () => {
      if (ref.current && !ref.current.disposed) {
        ref.current[Symbol.dispose]();
      }
    };
  }, []);

  return ref.current;
}

// packages/adapter-solid/src/use-view-model.ts
import { onCleanup } from "solid-js";
import type { ViewModel } from "@xndrjs/core";

/**
 * Hook that creates and manages a ViewModel instance with automatic cleanup.
 * The ViewModel is created once and automatically disposed when the component is cleaned up.
 *
 * @param factory - Function that creates the ViewModel instance (called only once)
 * @returns The ViewModel instance
 *
 * @example
 * ```tsx
 * import { useViewModel } from '@xndrjs/adapter-solid';
 * import { useReactiveValue } from '@xndrjs/adapter-solid';
 *
 * class CounterVM extends ViewModel {
 *   count = new ReactiveValue(0);
 *   doubled = createComputed(this.count)
 *     .as((c) => c * 2)
 *     .for(this);
 *
 *   increment() {
 *     this.count.set((prev) => prev + 1);
 *   }
 * }
 *
 * function Counter() {
 *   const vm = useViewModel(() => new CounterVM());
 *   const count = useReactiveValue(() => vm.count);
 *   const doubled = useReactiveValue(() => vm.doubled);
 *
 *   return (
 *     <div>
 *       <div>Count: {count()}</div>
 *       <div>Doubled: {doubled()}</div>
 *       <button onClick={() => vm.increment()}>+</button>
 *     </div>
 *   );
 * }
 * ```
 */
export function useViewModel<T extends ViewModel>(factory: () => T): T {
  const vm = factory();

  onCleanup(() => {
    vm[Symbol.dispose]();
  });

  return vm;
}
