// apps/demo-svelte/src/components/event-log/event-log.connector.svelte
<script lang="ts">
  import { ReactiveArray } from "@xndrjs/core";
  import { AppEventHandlers } from "@xndrjs/demo-common";
  import type { AppEvent } from "@xndrjs/demo-common";
  import type { StatePort } from "@xndrjs/core";
  import { eventBus } from "../../messaging";
  import { reactiveValue } from "@xndrjs/adapter-svelte";
  import EventLogView from "./event-log.view.svelte";

  const eventLogPort: StatePort<AppEvent[]> = new ReactiveArray<AppEvent>([]);
  const eventHandlers = new AppEventHandlers(eventBus, eventLogPort);

  const eventLogStore = reactiveValue(() => eventLogPort);
</script>

<div class="demo-section">
  <h2>Event Log</h2>
  <EventLogView
    events={$eventLogStore}
    onClear={() => eventHandlers.clearEventLog(eventLogPort)}
  />
</div>

// apps/demo-react/src/components/event-log/event-log.connector.tsx
import { useMemo } from "react";
import { useCreateStatePort, useReactiveValue } from "@xndrjs/adapter-react";
import { AppEventHandlers } from "@xndrjs/demo-common";
import { eventBus } from "../../messaging";
import { EventLogView } from "./event-log.view";
import type { AppEvent } from "@xndrjs/demo-common";

export function useEventLog() {
  // Create StatePort directly (standard approach)
  const eventLogPort = useCreateStatePort<AppEvent[]>([]);

  // Create AppEventHandlers with global EventBus and StatePort
  // Event handlers are automatically registered in the constructor
  const appEventHandlers = useMemo(
    () => new AppEventHandlers(eventBus, eventLogPort),
    [eventLogPort],
  );

  return {
    eventLogPort,
    eventHandlers: appEventHandlers,
  };
}

export function EventLogConnector() {
  const { eventLogPort, eventHandlers } = useEventLog();
  const eventLog = useReactiveValue(eventLogPort);

  return (
    <div className="demo-section">
      <h2>Event Log</h2>
      <EventLogView
        events={eventLog}
        onClear={() => eventHandlers.clearEventLog(eventLogPort)}
      />
    </div>
  );
}
